### PR TITLE
fix(#504): escape whitespaces in path when converting forms

### LINKED ISSUE #504: Error when converting form when path contains spaces
**Describe the bug**
If the file path for the directory containing the config includes spaces, this causes the `convert-*-forms` actions (and perhaps others?) to fail.

```
daudi@LAPTOP-5RIPOR8D /m/c/U/d/D/e/s/config-echis-2.0 (main)> cht --url=https://user:pass@localhost --accept-self-signed-certs convert-app-forms -- death_report
INFO Processing config in config-echis-2.0.
INFO Actions:
          convert-app-forms
INFO Starting action: convert-app-forms...
INFO Converting form /mnt/c/Users/david.njuguna/Desktop/eCHIS workshop/source code/config-echis-2.0/forms/app/death_report.xlsx....
usage: xls2xform-medic [-h] [--json] [--skip_validate]
          path_to_XLSForm output_path
xls2xform-medic: error: unrecognized arguments: code/config-echis-2.0/forms/app/death_report.xlsx /mnt/c/Users/david.njuguna/Desktop/
eCHIS workshop/source code/config-echis-2.0/forms/app/death_report.xml
INFO usage: xls2xform-medic [-h] [--json] [--skip_validate]
          path_to_XLSForm output_path
xls2xform-medic: error: unrecognized arguments: code/config-echis-2.0/forms/app/death_report.xlsx /mnt/c/Users/david.njuguna/Desktop/
eCHIS workshop/source code/config-echis-2.0/forms/app/death_report.xml
ERROR undefined
daudia LAPTOP-5RIPOR8D /m/c/U/d/D/e/s/config-echis-2.0 (main) [1]> 
```

**To Reproduce**
1. Store your config in a directory that includes a space in one of the folder names
2. Run a `convert-*-form` action

**Expected behavior**
I think we should be able to properly handle spaces in the path by properly escaping them before passing it to the `xls2xform-medic` command.

**Environment**
- cht-conf version: 3.15.0

**Additional Context**
Originally reported [on the forum](https://forum.communityhealthtoolkit.org/t/errors-when-converting-app-forms/2148).

### PR DESCRIPTION
**Pull request by andrablaj**
# Description

Escapes whitespaces in path before converting forms.

Closes #504 

# Code review items

- Readable: Concise, well named, follows the [style guide](https://docs.communityhealthtoolkit.org/contribute/code/style-guide/), documented if necessary.
- Documented: Configuration and user documentation on [cht-docs](https://github.com/medic/cht-docs/)
- Tested: Unit and/or integration tests where appropriate
- Backwards compatible: Works with existing data and configuration. Any breaking changes documented in the release notes.

# License

The software is provided under AGPL-3.0. Contributions to this project are accepted under the same license.

### CODE REVIEW

File: src/lib/convert-forms.js [hunk 1]
```diff
@@ -4,6 +4,7 @@ const argsFormFilter = require('./args-form-filter');
 const exec = require('./exec-promise');
 const fs = require('./sync-fs');
 const { getFormDir } = require('./forms-utils');
+const { escapeWhitespacesInPath } = require('./forms-utils');
```
Comment (latin-panda) [inline src/lib/convert-forms.js:7]: is possible to do this `const { getFormDir , escapeWhitespacesInPath } = require('./forms-utils')` here?

**Review by latin-panda — CHANGES_REQUESTED** [review]
Very nice! Just a question in line

File: src/lib/convert-forms.js (hunk 1 above)
Comment (andrablaj) [reply src/lib/convert-forms.js]: Oh, great one! thanks, just applied it

**Review by latin-panda — APPROVED** [review]
Sparkling✨✨
